### Get all clients
GET http://localhost:3000/api/clients

# ============================================================================
# SEARCHS
# ============================================================================

### Search by name
GET http://localhost:3000/api/clients/search?q=pedro

### Search by name - minimum 2 characters
GET http://localhost:3000/api/clients/search?q=pe

# ============================================================================
# CRUD
# ============================================================================

### Get a client by DNI
GET http://localhost:3000/api/clients/12345678


### Create new client
POST http://localhost:3000/api/clients/
Content-Type: application/json

{
  "dni":"12345678",
  "name": "Lautaro Herrera",
  "email": "lautaro.herrera@example.com",
  "address": "Av. Pellegrini 1234, Rosario, Santa Fe",
  "phone": "3416007788"
}

### Modify client (PATCH - partial modifications)
PATCH http://localhost:3000/api/clients/12345678
Content-Type: application/json

{
  "name": "Lautaro FERNANDEZ",
  "email": "lautaro.herrera@example.com",
  "address": "Cochabamba 230, Rosario, Santa Fe",
  "phone": "3416007788"
}

### Delete a client
DELETE http://localhost:3000/api/clients/12345678