### Obtener todos los clientes
GET http://localhost:3000/api/clients

# ============================================================================
# BÚSQUEDAS
# ============================================================================

### Búsqueda por nombre
GET http://localhost:3000/api/clients/search?q=pedro

### Búsqueda por nombre - mínimo 2 caracteres
GET http://localhost:3000/api/clients/search?q=He

# ============================================================================
# CRUD
# ============================================================================

### Obtener un cliente por DNI
GET http://localhost:3000/api/clients/12345678


### Crear nuevo cliente
POST http://localhost:3000/api/clients/
Content-Type: application/json

{
  "dni":"12345678",
  "name": "Lautaro Herrera",
  "email": "lautaro.herrera@example.com",
  "address": "Av. Pellegrini 1234, Rosario, Santa Fe",
  "phone": "3416007788"
}

### Modificar cliente (PATCH - modificaciones parciales)
PATCH http://localhost:3000/api/clients/12345678
Content-Type: application/json

{
  "name": "Lautaro FERNANDEZ",
  "email": "lautaro.herrera@example.com",
  "address": "Cochabamba 230, Rosario, Santa Fe",
  "phone": "3416007788"
}

### Borrar un cliente
DELETE http://localhost:3000/api/clients/12345678