### Listar
GET http://localhost:3000/api/distributors

### Buscar por texto (nombre o dni)
GET http://localhost:3000/api/distributors/search?q=delprato


### Obtener por dni
GET http://localhost:3000/api/distributors/16254545


### Crear
POST http://localhost:3000/api/distributors
Content-Type: application/json

{
"dni": "16254545",
"name": "Delprato Luca",
"address": "Av. Siempreviva 742",
"phone": "+54 341 555-1111",
"email": "delpra@gmail.com",
"productsIds": [1,2,5],
"zoneId": "1"
}


### Actualizar (reemplaza productos asociados si envías productosIds)
PATCH http://localhost:3000/api/distributors/16254545
Content-Type: application/json

{
"direccion": "San Martín 1234",
"productosIds": [2,3]
}


### Eliminar
DELETE http://localhost:3000/distribuidores/1