### List all distributors
GET http://localhost:3000/api/distributors

# ============================================================================
# SEARCHS
# ============================================================================

### Search by name (default)
GET http://localhost:3000/api/distributors/search?q=Luca

### Search by name (explicit)
GET http://localhost:3000/api/distributors/search?q=Luca&by=name

### Search by zone
GET http://localhost:3000/api/distributors/search?q=Centro&by=zone

### Search by zone - minimum 2 characters
GET http://localhost:3000/api/distributors/search?q=Ce&by=zone

# ============================================================================
# CRUD
# ============================================================================

### Get by dni
GET http://localhost:3000/api/distributors/16254545


### Create
POST http://localhost:3000/api/distributors
Content-Type: application/json

{
"dni": "16254545",
"name": "Delprato Luca",
"address": "Av. Siempreviva 742",
"phone": "+54 341 555-1111",
"email": "delpra@gmail.com",
"productsIds": [1,2,5],
"zoneId": "1"
}


### Update (replaces associated products if you send productsIds)
PATCH http://localhost:3000/api/distributors/16254545
Content-Type: application/json

{
"address": "San Martín 1234",
"productsIds": [2,3]
}

### Delete
DELETE http://localhost:3000/api/distributors/16254545