###listar las ventas

GET http://localhost:3000/api/ventas

###Crear venta

POST http://localhost:3000/api/ventas
Content-Type: application/json

{
  "clienteDni": "20909090",
  "persona": {
    "nombre":"juan",
    "email":"juanq@email.com"
  },
  "detalles": [
    {
      "productoId": 3,
      "cantidad": 3
    },
    {
      "productoId": 2,
      "cantidad": 1
    }
  ]
}

###Borrar una venta
DELETE http://localhost:3000/api/ventas/27