###obtener todas las autoridades
GET http://localhost:3000/api/autoridades

###obtener una autoridad
GET http://localhost:3000/api/autoridades/10101013

### Crear nueva autoridad
POST http://localhost:3000/api/autoridades
Content-Type: application/json

{
  "dni": "10101015",
  "nombre": "Juan Fernandez",
  "email":"jferndez@gmail.com",
  "direccion":"",
  "telefono":"",
  "rango": "1",
  "zonaId": "1"
}

###modificar autoridad (PUT - idempotente, modificaciones completas)
PUT http://localhost:3000/api/autoridades/10101013
Content-Type: application/json

{
  "nombre": "Lautaro FERNANDEZ",
  "rango": "3",
  "zonaId": "1"
}


###modificar autoridad (PATCH - no necesariamente idempotente, modificaciones parciales)
PATCH http://localhost:3000/api/autoridades/10101013
Content-Type: application/json

{
  "rango":"2"
}

###borrar una autoridad
DELETE http://localhost:3000/api/autoridades/10101015
