### Get all authorities
GET http://localhost:3000/api/authorities

### Get an authority by DNI
GET http://localhost:3000/api/authorities/10101015

### Search authorities by name
GET http://localhost:3000/api/authorities/search?q=Juan

### Search authorities by zone
GET http://localhost:3000/api/authorities?zone=Centro

### Search authorities by name and filter by zone
GET http://localhost:3000/api/authorities/search?q=Juan&zone=Centro

### Search authorities by name and filter by rank
GET http://localhost:3000/api/authorities/search?q=Juan&rank=1

### Filter authorities by zone and rank (without name search)
GET http://localhost:3000/api/authorities/search?zone=Centro&rank=1

### Get bribes from an authority
GET http://localhost:3000/api/authorities/10101015/bribes

### Get bribes from an authority with filters
GET http://localhost:3000/api/authorities/10101015/bribes?paid=true&minAmount=100&maxAmount=500&page=1&limit=5

#=======================================================================
#CRUD
#=======================================================================

### 9. Create new authority
POST http://localhost:3000/api/authorities
Content-Type: application/json
{
  "dni": "10101010",
  "name": "Juan Fernandez",
  "email":"jferndez@gmail.com",
  "adress":"",
  "phone":"",
  "rank": "1",
  "zoneId": "1"
}

### 10. Modify authority (PUT - idempotent, full modifications)
PUT http://localhost:3000/api/authorities/10101015
Content-Type: application/json
{
  "name": "Lautaro FERNANDEZ",
  "rank": "3",
  "zoneId": "1"
}

### 11. Modify authority (PATCH - partial modifications)
PATCH http://localhost:3000/api/authorities/10101015
Content-Type: application/json
{
  "rank":"2"
}

### 12. Delete an authority
DELETE http://localhost:3000/api/authorities/10101010