###obtener todos los clientes
GET http://localhost:3000/api/clientes

###obtener un cliente
GET http://localhost:3000/api/clientes/12345678


### Crear nuevo cliente
POST http://localhost:3000/api/clientes/
Content-Type: application/json

{
  "dni":"12345678",
  "nombre": "Lautaro Herrera",
  "email": "lautaro.herrera@example.com",
  "direccion": "Av. Pellegrini 1234, Rosario, Santa Fe",
  "telefono": "3416007788"
}

###modificar nuevo cliente (PUT - idempotente, modificaciones completas)
PUT http://localhost:3000/api/clientes/12345678
Content-Type: application/json

{
  "nombre": "Lautaro FERNANDEZ",
  "email": "lautaro.herrera@example.com",
  "direccion": "Av. Pellegrini 1234, Rosario, Santa Fe",
  "telefono": "3416007788"
}


###modificar nuevo cliente (PATCH - no necesariamente idempotente, modificaciones parciales)
PATCH http://localhost:3000/api/clientes/12345678
Content-Type: application/json

{
  "direccion":"Cochabamba 230, Rosario, Santa Fe"
}

###borrar un cliente
DELETE http://localhost:3000/api/clientes/12345678