POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "admin@local.dev",
  "password": "admin123"
}

###obtener todas las autoridades
GET http://localhost:3000/api/autoridades
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImM1NzFkNDYwLWVkMDUtNDcyOC04YjM5LWYxNmI5MTg2MDNiNiIsInJvbCI6IkFETUlOIiwiaWF0IjoxNzUzNDcxMDA4LCJleHAiOjE3NTM0NzQ2MDh9.uda19RwcOq_wZSS0U8ShNo5kw-9w_iiMQHgOb5CHu2g

###obtener una autoridad
GET http://localhost:3000/api/autoridades/12345678
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImM1NzFkNDYwLWVkMDUtNDcyOC04YjM5LWYxNmI5MTg2MDNiNiIsInJvbCI6IkFETUlOIiwiaWF0IjoxNzUzNDcxMDA4LCJleHAiOjE3NTM0NzQ2MDh9.uda19RwcOq_wZSS0U8ShNo5kw-9w_iiMQHgOb5CHu2g

### Crear nueva autoridad
POST http://localhost:3000/api/autoridades/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImM1NzFkNDYwLWVkMDUtNDcyOC04YjM5LWYxNmI5MTg2MDNiNiIsInJvbCI6IkFETUlOIiwiaWF0IjoxNzUzNDcxMDA4LCJleHAiOjE3NTM0NzQ2MDh9.uda19RwcOq_wZSS0U8ShNo5kw-9w_iiMQHgOb5CHu2g

{
  "dni": "12345678",
  "nombre": "Lautaro Herrera",
  "rango": "1",
  "zonaId": 1
}



###modificar autoridad (PUT - idempotente, modificaciones completas)
PUT http://localhost:3000/api/autoridades/12345678
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImM1NzFkNDYwLWVkMDUtNDcyOC04YjM5LWYxNmI5MTg2MDNiNiIsInJvbCI6IkFETUlOIiwiaWF0IjoxNzUzNDcxMDA4LCJleHAiOjE3NTM0NzQ2MDh9.uda19RwcOq_wZSS0U8ShNo5kw-9w_iiMQHgOb5CHu2g

{
  "dni": "12345678",
  "nombre": "Lautaro FERNANDEZ",
  "rango": "1",
  "zonaId": 1
}


###modificar autoridad (PATCH - no necesariamente idempotente, modificaciones parciales)
PATCH http://localhost:3000/api/autoridades/12345678
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImM1NzFkNDYwLWVkMDUtNDcyOC04YjM5LWYxNmI5MTg2MDNiNiIsInJvbCI6IkFETUlOIiwiaWF0IjoxNzUzNDcxMDA4LCJleHAiOjE3NTM0NzQ2MDh9.uda19RwcOq_wZSS0U8ShNo5kw-9w_iiMQHgOb5CHu2g

{
  "rango":"2"
}

###borrar una autoridad
DELETE http://localhost:3000/api/autoridades/12345678
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImM1NzFkNDYwLWVkMDUtNDcyOC04YjM5LWYxNmI5MTg2MDNiNiIsInJvbCI6IkFETUlOIiwiaWF0IjoxNzUzNDcxMDA4LCJleHAiOjE3NTM0NzQ2MDh9.uda19RwcOq_wZSS0U8ShNo5kw-9w_iiMQHgOb5CHu2g