###obtener todos los sobornos
GET http://localhost:3000/api/bribes

###obtener un soborno
GET http://localhost:3000/api/bribes/1

###buscar sobornos
GET http://localhost:3000/api/bribes/search?q=true

###pagar soborno
PATCH http://localhost:3000/api/bribes/10101013/pay
Content-Type: application/json

{
  "ids":[1]
}

###pagar sobornos
PATCH http://localhost:3000/api/bribes/pay
Content-Type: application/json

{
  "ids":
  [
    2,3,5
  ]
}

###borrar un soborno: NO PERMITIDO