###listar las ventas

GET http://localhost:3000/api/sales

###listar las ventas
GET http://localhost:3000/api/sales/search?date=2025-10-03&type=exact
###Crear venta
POST http://localhost:3000/api/sales
Content-Type: application/json

{
  "clientDni": "20909090",
  "person": {
    "name":"juan",
    "email":"juanq@email.com"
  },
  "details": [
    {
      "productId": 1,
      "quantity": 1
    }
  ]
}

###Borrar una venta: NO PERMITIDO