POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "admin@local.dev",
  "password": "admin123"
}
###
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "lauti@email.com",
  "password":"1234a@A1"
}

###
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "username": "lauta",
  "email": "lautaa@email.com",
  "password":"1234a@A1"
}

###
GET http://localhost:3000/api/users

###
POST http://localhost:3000/api/auth/logout