GET http://localhost:3000/api/usuarios
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZjNjExNTU1LTQ1OTEtNDA2MS05MGMzLWQ5ZWNhYmExMzUxNyIsInJvbCI6IkFETUlOIiwiaWF0IjoxNzUyODc3NzUwLCJleHAiOjE3NTI4ODEzNTB9.HI0ASFOB5yMUMMz4ZCT0teCJ2FdeA0RvhaxaRK6IQu8
