###obtener todos los clientes
GET http://localhost:3000/api/clientes

###obtener un cliente
GET http://localhost:3000/api/clientes/10

### Crear nuevo cliente
POST http://localhost:3000/api/clientes/
Content-Type: application/json

{
  "id": 2,
  "nombre":"Fernanda",
  "direccion":"Cochabamba 230",
  "regCompras":"2 paquetes de galletitas",
  "tel": "03402555777",
  "correo":"fer@gmail.com"
}


###modificar nuevo cliente (PUT - idempotente, modificaciones completas)
PUT http://localhost:3000/api/clientes/2
Content-Type: application/json

{
  "id": 2,
  "nombre":"Fernanda",
  "direccion":"Cochabamba 230",
  "regCompras":"3 paquetes de galletitas",
  "tel": "03402555778",
  "correo":"fer@gmail.com"
}


###modificar nuevo cliente (PATCH - no necesariamente idempotente, modificaciones parciales)
PATCH http://localhost:3000/api/clientes/2
Content-Type: application/json

{
  "id": 2,
  "nombre":"Fernanda",
  "direccion":"Cochabamba 230",
  "regCompras":"3 paquetes de galletitas",
  "tel": "03402555778",
  "correo":"fer@gmail.com"
}

###borrar un cliente
DELETE http://localhost:3000/api/clientes/2
