###obtener todos los clientes
GET http://localhost:3000/api/clientes

###obtener un cliente
GET http://localhost:3000/api/clientes/44d6c6e3-c9ad-479f-aa11-1a8034bde6a5


### Crear nuevo cliente
POST http://localhost:3000/api/clientes/
Content-Type: application/json

{
  "nombre": "Lautaro Herrera",
  "email": "lautaro.herrera@example.com",
  "direccion": "Av. Pellegrini 1234, Rosario, Santa Fe",
  "telefono": "3416007788"
}



###modificar nuevo cliente (PUT - idempotente, modificaciones completas)
PUT http://localhost:3000/api/clientes/373360ce-12d0-4bc8-a26c-df4bccf0f8ff
Content-Type: application/json

{
  "nombre": "Lautaro FERNANDEZ",
  "email": "lautaro.herrera@example.com",
  "direccion": "Av. Pellegrini 1234, Rosario, Santa Fe",
  "telefono": "3416007788"
}


###modificar nuevo cliente (PATCH - no necesariamente idempotente, modificaciones parciales)
PATCH http://localhost:3000/api/clientes/44d6c6e3-c9ad-479f-aa11-1a8034bde6a5
Content-Type: application/json

{
  "direccion":"Cochabamba 230, Rosario, Santa Fe"
}

###borrar un cliente
DELETE http://localhost:3000/api/clientes/0969c67b-9a96-4618-a72a-f07a714e7719