### Obtener todos los productos
GET http://localhost:3000/api/products

###
GET http://localhost:3000/api/products/search?q=Fernet


### Obtener un producto por ID
GET http://localhost:3000/api/products/1
### Crear nuevo producto
POST http://localhost:3000/api/products
Content-Type: application/json

{
  "description": "Hambugeruesa con queso",
  "price": 1000,
  "stock": 10,
  "isIllegal": true
}

### Modificar producto (reemplazo completo)
PATCH http://localhost:3000/api/products/1
Content-Type: application/json

{
  "description": "Fernet Branca",
  "price": 800,
  "stock": 150,
  "isIllegal": false
}

### Modificar producto (PATCH - actualización parcial)
PATCH http://localhost:3000/api/productos/3
Content-Type: application/json

{
  "stock": 120
}

### Borrar un producto
DELETE http://localhost:3000/api/products/2

