### Get all products
GET http://localhost:3000/api/products

# ============================================================================
# SEARCHS
# ============================================================================

### Search by description
GET http://localhost:3000/api/products/search?q=Fernet

### Search by description - minimum 2 characters
GET http://localhost:3000/api/products/search?q=Ha

### Search legal products (isIllegal=false)
GET http://localhost:3000/api/products/search?by=legal&q=true

### Search illegal products (isIllegal=true)
GET http://localhost:3000/api/products/search?by=legal&q=false

### Search by minimum price
GET http://localhost:3000/api/products/search?min=500

### Search by maximum price
GET http://localhost:3000/api/products/search?max=1000

### Search by price range (between 500 and 1000)
GET http://localhost:3000/api/products/search?min=500&max=1000

### Search by exact price (using equal min and max)
GET http://localhost:3000/api/products/search?min=800&max=800

# ============================================================================
# CRUD
# ============================================================================

### Get a product by ID
GET http://localhost:3000/api/products/1
### Create new product
POST http://localhost:3000/api/products
Content-Type: application/json

{
  "description": "Cheeseburger",
  "price": 1000,
  "stock": 10,
  "isIllegal": true
}

### Modify product (full replacement)
PATCH http://localhost:3000/api/products/1
Content-Type: application/json

{
  "description": "Fernet Branca",
  "price": 800,
  "stock": 150,
  "isIllegal": false
}

### Modify product (PATCH - partial update)
PATCH http://localhost:3000/api/products/4
Content-Type: application/json

{
  "stock": 120
}

### Mark product as illegal
PATCH http://localhost:3000/api/products/4
Content-Type: application/json

{
  "isIllegal": true
}

### Delete a product
DELETE http://localhost:3000/api/products/4