###obtener todas las zonas
GET http://localhost:3000/api/zonas

###obtener una zona
GET http://localhost:3000/api/zonas/1

### Crear nueva zona
POST http://localhost:3000/api/zonas
Content-Type: application/json

{
  "nombre": "Centro"
}

###modificar nueva zona(PATCH - no necesariamente idempotente, modificaciones parciales)
PATCH http://localhost:3000/api/zonas/10
Content-Type: application/json

{
  "nombre": "sur"
}

###modificar una zona
PATCH http://localhost:3000/api/zonas/1
Content-Type: application/json

{
  "esSedeCentral":false
}

###borrar una zona
DELETE http://localhost:3000/api/zonas/3
