POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "admin@local.dev",
  "password": "admin123"
}

###obtener todas las zonas
GET http://localhost:3000/api/zonas

###obtener una zona
GET http://localhost:3000/api/zonas/1


### Crear nueva zona
POST http://localhost:3000/api/zonas
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAxOTk2M2UwLWEzZGItNzJlOC05NGRmLWRiM2QzODNhNjU0MCIsInJvbGVzIjpbIkFETUlOIl0sImlhdCI6MTc1ODM5MTc2OCwiZXhwIjoxNzU4Mzk1MzY4fQ.-iHYPWIWkaDMRC_8GcNiZHW-cKAIP56kHoPIFO59ARM

{
  "nombre": "Zona centro"
}



###modificar nueva zona (PUT - idempotente, modificaciones completas)
PUT http://localhost:3000/api/zonas/2
Content-Type: application/json

{
  "nombre":"Zona sur"
}


###modificar nueva zona(PATCH - no necesariamente idempotente, modificaciones parciales)
PATCH http://localhost:3000/api/zonas/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAxOTk2M2UwLWEzZGItNzJlOC05NGRmLWRiM2QzODNhNjU0MCIsInJvbGVzIjpbIkFETUlOIl0sImlhdCI6MTc1ODM4ODk3NywiZXhwIjoxNzU4MzkyNTc3fQ.jXuiH4GZdyzVBUB16CjTsPC2Pz5TOJB0hbcnIq1T0KM

{
  "esSedeCentral": false
}

###borrar una zona
DELETE http://localhost:3000/api/zonas/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAxOTk2M2UwLWEzZGItNzJlOC05NGRmLWRiM2QzODNhNjU0MCIsInJvbGVzIjpbIkFETUlOIl0sImlhdCI6MTc1ODM5MTc2OCwiZXhwIjoxNzU4Mzk1MzY4fQ.-iHYPWIWkaDMRC_8GcNiZHW-cKAIP56kHoPIFO59ARM