###
GET http://localhost:3000/api/tematicas

###
GET http://localhost:3000/api/tematicas/5

###
GET http://localhost:3000/api/topics/search?q=Gastronomía
###
POST http://localhost:3000/api/topics
Content-Type: application/json

{
  "description":"Gastronomía"
}

###
PATCH http://localhost:3000/api/tematicas/5
Content-Type: application/json

{
  "descripcion":"Retenciones"
}

###
DELETE http://localhost:3000/api/tematicas/4